(let* ((p (new-prompt))
       (subcont (push-prompt p (lambda (dummy) (+ 3 (with-subcont p (lambda (subcont) subcont)))))))
  (display (push-subcont subcont (lambda (dummy) 5))))

(let* ((reifyP (lambda (p) (lambda (sk) (lambda (v) (push-prompt p (lambda (dummy) (push-subcont sk (lambda (dummy) v))))))))
       (shift (lambda (p) (lambda (f) (with-subcont p (lambda (sk) (push-prompt p (lambda (dummy) (f ((reifyP p) sk)))))))))
       (control (lambda (p) (lambda (f) (with-subcont p (lambda (sk) (push-prompt p (lambda (dummy) (f (lambda (v) (push-subcont sk (lambda (dummy) v)))))))))))
       (myabort (lambda (p) (lambda (x) (with-subcont p (lambda (dummy) x)))))
       (p (new-prompt))
       (dummy (display (push-prompt p (lambda (dummy) 123)))))
    (display (push-prompt p (lambda (dummy) (+ 1 ((shift p) (lambda (k) 42)))))))
