(letrec ((even? (lambda (n) (if (= n 0) #t (odd? (- n 1)))))
         (odd? (lambda (n) (if (= n 0) #f (even? (- n 1))))))
  (let ((a (display (even? 100)))
        (b (display (even? 101)))
        (c (display (even? 1000)))
        (d (display (even? 1001))))
        #t))
